package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BumpPaperVersion'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BumpPaperVersion")) {
    params {
        expect {
            password("env.GITHUB_TOKEN", "%github.token%", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.GITHUB_TOKEN", "credentialsJSON:919ad344-a80a-4139-8c4f-c785dd11512d", display = ParameterDisplay.HIDDEN)
        }
    }
}
