package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publish")) {
    params {
        expect {
            password("env.NEXUS_PASSWORD", "credentialsJSON:f702f75c-65dc-4d75-a035-cb0179b7f1ea", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.NEXUS_PASSWORD", "credentialsJSON:ca67d186-8118-4078-b1da-d5dde98cb9e6", display = ParameterDisplay.HIDDEN)
        }
    }
}
